name = "hereisorder"
main = "src/index.ts"
compatibility_date = "2026-03-02"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[observability.logs]
enabled = true
persist = true
invocation_logs = true
head_sampling_rate = 1

# Cloudflare Pages/Workers runtime binding for D1
[[d1_databases]]
binding = "DB"
database_name = "hereisorder"
database_id = "6129977e-f5a1-41ee-96ce-7a7a1e260e6d"
